/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function checksumEvm(address: string, chainId?: number | undefined | null): string

export declare function compareAddresses(a: string, b: string): string

export declare function detectNetworks(address: string): string

export declare function isValid(address: string, network: string): boolean

export declare function validate(address: string): string

export declare function validateForNetwork(address: string, network: string): string
